name: Create-PR
description: Creates a pull request using Claude Code to solve a Linear issue with full context
author: https://github.com/buildkite
requirements:
  - docker
configuration:
  properties: {}
  additionalProperties: false
