#!/bin/bash

set -ueo pipefail

HOOKS_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

echo "Copying generate-pr from $HOOKS_DIR/../bin/generate-pr to /generate-pr"
cp $HOOKS_DIR/../bin/generate-pr $BUILDKITE_BUILD_CHECKOUT_PATH/generate-pr
chmod u+x $BUILDKITE_BUILD_CHECKOUT_PATH/generate-pr

ls -al $BUILDKITE_BUILD_CHECKOUT_PATH

echo "Attempting to check out repo"
cd $BUILDKITE_BUILD_CHECKOUT_PATH
mkdir -p first-draft-repo
cd first-draft-repo
git clone https://github.com/buildkite/buildkite.git
echo "Cloned"

echo "Copying generate-pr from $HOOKS_DIR/../bin/generate-pr to $BUILDKITE_BUILD_CHECKOUT_PATH/first-draft-repo/generate-pr"
cp $HOOKS_DIR/../bin/generate-pr $BUILDKITE_BUILD_CHECKOUT_PATH/first-draft-repo/generate-pr
chmod u+x $BUILDKITE_BUILD_CHECKOUT_PATH/first-draft-repo/generate-pr

ls -al
